### ISSUE TITLE
Change map background to image

### ISSUE THREAD

**Issue by BlueDrink9** [R-Rudolph/OmegaRPG#6]
I might be missing something, but is it possible to use an image (i.e. an actual map) as the background?

Also, as an aside, is it possible to split the map into a separate window/make it take up more of the main window?

**Comment by R-Rudolph** [comment]
Hi @BlueDrink9 .

There is no direct background image feature, however you can insert a big miniature and set its layer to "Background". This allows you to move it around like a miniature. Additionally there is the Lock Background option in the Map Settings, which prevents accidentally moving/editing background miniatures.

The map cannot be moved to a separate window, but you can increase its size. It is in a Splitter with the chat area, you can drag it down with the grey handle that should be just beneath the Map Toolbar and above the Channel Tabs.

**Comment by BlueDrink9** [comment]
Thank you!

**Comment by R-Rudolph** [comment]
No prob :-)
